@baseUrl = http://127.0.0.1:8000
# @baseUrl = https://backend-avonqr.vercel.app

### LOGIN (Autenticación de usuario)
# @name Login
# Endpoint para obtener el token JWT.
# Retorna:
#   - access_token (string): Token JWT de autenticación.
#   - token_type (string): Tipo de token (bearer).
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "account_user": "admin",
  "account_password": "123456789"
}
